# Generated by Django 4.0.4 on 2022-07-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'departments',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('type_of_work', models.CharField(choices=[('article', 'Article'), ('project', 'Educational Project'), ('seminer', 'Seminer'), ('script', 'Scripts')], max_length=16)),
                ('pages', models.CharField(max_length=16)),
                ('chapters', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projectStore.department')),
            ],
            options={
                'ordering': ('topic',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
