# Generated by Django 4.0.4 on 2022-07-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='subject',
        ),
    ]
