# Generated by Django 4.0.4 on 2022-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=120)),
                ('select_work_type', models.CharField(choices=[('Article', 'Article'), ('Project', 'Educational Project'), ('Seminner', 'Seminner'), ('Other', 'Other')], max_length=64)),
                ('clasification', models.CharField(choices=[('Post-graduate', 'Post-graduate'), ('undergraduate', 'Degree'), ('HND', 'Higher National Diploma'), ('ND', 'National Diploma'), ('NCE', 'Nigeria Certificate In Education')], max_length=64)),
                ('job_discribtion', models.TextField()),
            ],
        ),
    ]
